// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LifeTrack.Shared.Migrations.AuditDb
{
    /// <inheritdoc />
    public partial class InitialAuditCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // AuditLogs table already created via SQL script
            // This migration is a placeholder so EF Core
            // tracks it in __EFMigrationsHistory
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Reverse not needed
        }
    }
}