// <auto-generated />
using System;
using LifeTrack.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace LifeTrack.Shared.Migrations.AuditDb
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LifeTrack.Shared.Models.AuditLog", b =>
            {
                b.Property<long>("AuditID").ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditID"));
                b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("ActionTime").HasColumnType("datetime2");
                b.Property<string>("Details").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<long?>("EntityID").HasColumnType("bigint");
                b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("IPAddress").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<long>("UserID").HasColumnType("bigint");
                b.HasKey("AuditID");
                b.HasIndex("Action");
                b.HasIndex("ActionTime");
                b.HasIndex("UserID");
                b.ToTable("AuditLogs");
            });
#pragma warning restore 612, 618
        }
    }
}