// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LifeTrack.Shared.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Tables already created via SQL script
            // This migration is a placeholder so EF Core
            // tracks it in __EFMigrationsHistory
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Reverse not needed for initial create
        }
    }
}