// <auto-generated />
using System;
using LifeTrack.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeTrack.Shared.Migrations
{
    [DbContext(typeof(LifeTrackDbContext))]
    [Migration("20250512000000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            // Model snapshot is in LifeTrackDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}