// <auto-generated />
using System;
using LifeTrack.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeTrack.Shared.Migrations
{
    [DbContext(typeof(LifeTrackDbContext))]
    partial class LifeTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LifeTrack.Shared.Models.AdverseEvent", b =>
            {
                b.Property<long>("EventID").ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventID"));
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<long>("PatientID").HasColumnType("bigint");
                b.Property<long>("ProtocolID").HasColumnType("bigint");
                b.Property<DateTime>("ReportedDate").HasColumnType("datetime2");
                b.Property<string>("Severity").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("EventID");
                b.HasIndex("PatientID");
                b.ToTable("AdverseEvents");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Deviation", b =>
            {
                b.Property<long>("DeviationID").ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeviationID"));
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Severity").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<long>("SiteProtocolID").HasColumnType("bigint");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("DeviationID");
                b.HasIndex("SiteProtocolID");
                b.ToTable("Deviations");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Document", b =>
            {
                b.Property<long>("DocumentID").ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentID"));
                b.Property<long>("ProtocolID").HasColumnType("bigint");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Type").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("UploadedAt").HasColumnType("datetime2");
                b.Property<long>("UploadedBy").HasColumnType("bigint");
                b.Property<string>("Version").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("DocumentID");
                b.HasIndex("ProtocolID");
                b.HasIndex("UploadedBy");
                b.ToTable("Documents");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Enrollment", b =>
            {
                b.Property<long>("EnrollmentID").ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EnrollmentID"));
                b.Property<DateTime?>("ConsentDate").HasColumnType("datetime2");
                b.Property<DateTime>("EnrollmentDate").HasColumnType("datetime2");
                b.Property<long>("PatientID").HasColumnType("bigint");
                b.Property<long>("SiteProtocolID").HasColumnType("bigint");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("WithdrawalReason").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.HasKey("EnrollmentID");
                b.HasIndex("PatientID");
                b.HasIndex("SiteProtocolID");
                b.ToTable("Enrollments");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.KPIReport", b =>
            {
                b.Property<long>("ReportID").ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportID"));
                b.Property<int>("AECount").HasColumnType("int");
                b.Property<decimal>("DropoutRate").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<decimal>("EnrollmentRate").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                b.Property<DateTime>("GeneratedDate").HasColumnType("datetime2");
                b.Property<long>("ProtocolID").HasColumnType("bigint");
                b.Property<string>("Scope").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("ReportID");
                b.HasIndex("ProtocolID");
                b.ToTable("KPIReports");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Notification", b =>
            {
                b.Property<long>("NotificationID").ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationID"));
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("CreatedDate").HasColumnType("datetime2");
                b.Property<string>("Message").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<long>("UserID").HasColumnType("bigint");
                b.HasKey("NotificationID");
                b.HasIndex("UserID");
                b.ToTable("Notifications");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Patient", b =>
            {
                b.Property<long>("PatientID").HasColumnType("bigint");
                b.Property<string>("ContactInfo").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("DOB").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("PatientID");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Patients");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Protocol", b =>
            {
                b.Property<long>("ProtocolID").HasColumnType("bigint");
                b.Property<DateTime>("EndDate").HasColumnType("datetime2");
                b.Property<string>("Phase").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("StartDate").HasColumnType("datetime2");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("ProtocolID");
                b.ToTable("Protocols");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Role", b =>
            {
                b.Property<int>("RoleID").HasColumnType("int");
                b.Property<string>("RoleName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("RoleID");
                b.ToTable("Roles");
                b.HasData(
                    new { RoleID = 1, RoleName = "Admin" },
                    new { RoleID = 2, RoleName = "ClinicalTrialManager" },
                    new { RoleID = 3, RoleName = "Investigator" },
                    new { RoleID = 4, RoleName = "Patient" },
                    new { RoleID = 5, RoleName = "RegulatoryOfficer" },
                    new { RoleID = 6, RoleName = "DataManager" }
                );
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Site", b =>
            {
                b.Property<long>("SiteID").HasColumnType("bigint");
                b.Property<string>("Location").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("SiteID");
                b.ToTable("Sites");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.SiteProtocol", b =>
            {
                b.Property<long>("SiteProtocolID").ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SiteProtocolID"));
                b.Property<DateTime>("InitiationDate").HasColumnType("datetime2");
                b.Property<long>("InvestigatorID").HasColumnType("bigint");
                b.Property<long>("ProtocolID").HasColumnType("bigint");
                b.Property<long>("SiteID").HasColumnType("bigint");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("SiteProtocolID");
                b.HasIndex("InvestigatorID");
                b.HasIndex("ProtocolID");
                b.HasIndex("SiteID");
                b.ToTable("SiteProtocols");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.User", b =>
            {
                b.Property<long>("UserID").HasColumnType("bigint");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<int>("RoleID").HasColumnType("int");
                b.HasKey("UserID");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("RoleID");
                b.ToTable("Users");
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Visit", b =>
            {
                b.Property<long>("VisitID").ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VisitID"));
                b.Property<long>("EnrollmentID").HasColumnType("bigint");
                b.Property<string>("Notes").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("VisitDate").HasColumnType("datetime2");
                b.HasKey("VisitID");
                b.HasIndex("EnrollmentID");
                b.ToTable("Visits");
            });

            // Relationships
            modelBuilder.Entity("LifeTrack.Shared.Models.AdverseEvent", b =>
            {
                b.HasOne("LifeTrack.Shared.Models.Patient", "Patient")
                    .WithMany("AdverseEvents").HasForeignKey("PatientID")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Deviation", b =>
            {
                b.HasOne("LifeTrack.Shared.Models.SiteProtocol", "SiteProtocol")
                    .WithMany("Deviations").HasForeignKey("SiteProtocolID")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Document", b =>
            {
                b.HasOne("LifeTrack.Shared.Models.Protocol", "Protocol")
                    .WithMany("Documents").HasForeignKey("ProtocolID")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("LifeTrack.Shared.Models.User", "Uploader")
                    .WithMany().HasForeignKey("UploadedBy")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Enrollment", b =>
            {
                b.HasOne("LifeTrack.Shared.Models.Patient", "Patient")
                    .WithMany("Enrollments").HasForeignKey("PatientID")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("LifeTrack.Shared.Models.SiteProtocol", "SiteProtocol")
                    .WithMany("Enrollments").HasForeignKey("SiteProtocolID")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.KPIReport", b =>
            {
                b.HasOne("LifeTrack.Shared.Models.Protocol", "Protocol")
                    .WithMany("KPIReports").HasForeignKey("ProtocolID")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Notification", b =>
            {
                b.HasOne("LifeTrack.Shared.Models.User", "User")
                    .WithMany("Notifications").HasForeignKey("UserID")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.SiteProtocol", b =>
            {
                b.HasOne("LifeTrack.Shared.Models.User", "Investigator")
                    .WithMany().HasForeignKey("InvestigatorID")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("LifeTrack.Shared.Models.Protocol", "Protocol")
                    .WithMany("SiteProtocols").HasForeignKey("ProtocolID")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("LifeTrack.Shared.Models.Site", "Site")
                    .WithMany("SiteProtocols").HasForeignKey("SiteID")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.User", b =>
            {
                b.HasOne("LifeTrack.Shared.Models.Role", "Role")
                    .WithMany("Users").HasForeignKey("RoleID")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("LifeTrack.Shared.Models.Visit", b =>
            {
                b.HasOne("LifeTrack.Shared.Models.Enrollment", "Enrollment")
                    .WithMany("Visits").HasForeignKey("EnrollmentID")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}